-- EditorsTeam: per-user Fonto access, daily login analytics, and missing sales tables.
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.fonto_users (
  id uuid primary key default gen_random_uuid(),
  full_name text not null check (char_length(full_name) between 2 and 100),
  phone text not null unique check (phone ~ '^09[0-9]{9}$'),
  city text not null check (char_length(city) between 2 and 80),
  status text not null default 'pending' check (status in ('pending', 'approved', 'suspended')),
  password_hash text,
  requested_at timestamptz not null default now(),
  password_set_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.fonto_user_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.fonto_users(id) on delete cascade,
  token_hash bytea not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.fonto_login_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.fonto_users(id) on delete set null,
  logged_in_at timestamptz not null default now()
);

create table if not exists public.fonto_login_attempts (
  id bigint generated by default as identity primary key,
  phone text not null,
  request_ip text,
  successful boolean not null default false,
  attempted_at timestamptz not null default now()
);

create table if not exists public.fonto_registration_attempts (
  id bigint generated by default as identity primary key,
  request_ip text,
  attempted_at timestamptz not null default now()
);

create index if not exists fonto_users_status_requested_idx
  on public.fonto_users (status, requested_at desc);
create index if not exists fonto_sessions_token_active_idx
  on public.fonto_user_sessions (token_hash, expires_at) where revoked_at is null;
create index if not exists fonto_sessions_user_idx
  on public.fonto_user_sessions (user_id);
create index if not exists fonto_login_events_time_idx
  on public.fonto_login_events (logged_in_at desc);
create index if not exists fonto_login_events_user_idx
  on public.fonto_login_events (user_id);
create index if not exists fonto_login_attempts_guard_idx
  on public.fonto_login_attempts (phone, request_ip, attempted_at desc);
create index if not exists fonto_registration_attempts_guard_idx
  on public.fonto_registration_attempts (request_ip, attempted_at desc);

alter table public.fonto_users enable row level security;
alter table public.fonto_user_sessions enable row level security;
alter table public.fonto_login_events enable row level security;
alter table public.fonto_login_attempts enable row level security;
alter table public.fonto_registration_attempts enable row level security;

revoke all on table public.fonto_users from anon, authenticated;
revoke all on table public.fonto_user_sessions from anon, authenticated;
revoke all on table public.fonto_login_events from anon, authenticated;
revoke all on table public.fonto_login_attempts from anon, authenticated;
revoke all on table public.fonto_registration_attempts from anon, authenticated;

create or replace function public.fonto_normalize_phone(input_phone text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select regexp_replace(
    translate(coalesce(input_phone, ''), '۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩', '01234567890123456789'),
    '[^0-9]', '', 'g'
  );
$$;

create or replace function public.is_fonto_admin()
returns boolean
language sql
stable
set search_path = pg_catalog
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'fonto_admin')::boolean, false);
$$;

create or replace function public.register_fonto_user(
  input_full_name text,
  input_phone text,
  input_city text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  normalized_phone text := public.fonto_normalize_phone(input_phone);
  clean_name text := btrim(coalesce(input_full_name, ''));
  clean_city text := btrim(coalesce(input_city, ''));
  client_ip text := split_part(coalesce(current_setting('request.headers', true)::jsonb ->> 'x-forwarded-for', ''), ',', 1);
  recent_requests integer;
begin
  if clean_name = '' or char_length(clean_name) not between 2 and 100 then
    raise exception 'نام و نشان معتبر نیست';
  end if;
  if normalized_phone !~ '^09[0-9]{9}$' then
    raise exception 'شماره تماس باید با صفر و به‌صورت ۱۱ رقمی وارد شود';
  end if;
  if clean_city = '' or char_length(clean_city) not between 2 and 80 then
    raise exception 'نام شهر معتبر نیست';
  end if;

  select count(*) into recent_requests
  from public.fonto_registration_attempts
  where client_ip <> '' and request_ip = client_ip
    and attempted_at > now() - interval '1 hour';
  if recent_requests >= 10 then
    raise exception 'تعداد درخواست‌ها بیش از حد مجاز است؛ کمی بعد دوباره تلاش کنید';
  end if;

  insert into public.fonto_registration_attempts(request_ip) values (nullif(client_ip, ''));
  insert into public.fonto_users(full_name, phone, city)
  values (clean_name, normalized_phone, clean_city)
  on conflict (phone) do update
    set full_name = excluded.full_name,
        city = excluded.city,
        requested_at = now(),
        updated_at = now()
    where public.fonto_users.status <> 'approved';

  return jsonb_build_object(
    'ok', true,
    'message', 'درخواست شما ثبت شد؛ رمز عبور برای شما پیامک خواهد شد.'
  );
end;
$$;

create or replace function public.verify_fonto_user(
  input_phone text,
  input_password text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  normalized_phone text := public.fonto_normalize_phone(input_phone);
  client_ip text := split_part(coalesce(current_setting('request.headers', true)::jsonb ->> 'x-forwarded-for', ''), ',', 1);
  matched_user public.fonto_users%rowtype;
  failure_count integer;
  raw_token text;
begin
  if normalized_phone !~ '^09[0-9]{9}$' or coalesce(input_password, '') = '' then
    return jsonb_build_object('ok', false);
  end if;

  select count(*) into failure_count
  from public.fonto_login_attempts
  where phone = normalized_phone
    and coalesce(request_ip, '') = coalesce(client_ip, '')
    and successful = false
    and attempted_at > now() - interval '10 minutes';

  if failure_count >= 5 then
    return jsonb_build_object('ok', false, 'retry_after', 600);
  end if;

  select * into matched_user
  from public.fonto_users
  where phone = normalized_phone
    and status = 'approved'
    and password_hash is not null
  limit 1;

  if matched_user.id is null
     or matched_user.password_hash <> crypt(input_password, matched_user.password_hash) then
    insert into public.fonto_login_attempts(phone, request_ip, successful)
    values (normalized_phone, nullif(client_ip, ''), false);
    return jsonb_build_object('ok', false);
  end if;

  insert into public.fonto_login_attempts(phone, request_ip, successful)
  values (normalized_phone, nullif(client_ip, ''), true);
  insert into public.fonto_login_events(user_id) values (matched_user.id);

  delete from public.fonto_user_sessions where expires_at < now() - interval '1 day';
  raw_token := encode(gen_random_bytes(32), 'hex');
  insert into public.fonto_user_sessions(user_id, token_hash, expires_at)
  values (matched_user.id, digest(raw_token, 'sha256'), now() + interval '8 hours');

  return jsonb_build_object(
    'ok', true,
    'token', raw_token,
    'expires_at', now() + interval '8 hours',
    'full_name', matched_user.full_name
  );
end;
$$;

create or replace function public.validate_fonto_session(input_token text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  matched_session public.fonto_user_sessions%rowtype;
  matched_name text;
begin
  if coalesce(input_token, '') = '' then return jsonb_build_object('ok', false); end if;
  select s.* into matched_session
  from public.fonto_user_sessions s
  join public.fonto_users u on u.id = s.user_id
  where s.token_hash = digest(input_token, 'sha256')
    and s.revoked_at is null and s.expires_at > now() and u.status = 'approved'
  limit 1;
  if matched_session.id is null then return jsonb_build_object('ok', false); end if;
  update public.fonto_user_sessions set last_seen_at = now() where id = matched_session.id;
  select full_name into matched_name from public.fonto_users where id = matched_session.user_id;
  return jsonb_build_object('ok', true, 'full_name', matched_name, 'expires_at', matched_session.expires_at);
end;
$$;

create or replace function public.revoke_fonto_session(input_token text)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
begin
  update public.fonto_user_sessions
  set revoked_at = now()
  where token_hash = digest(coalesce(input_token, ''), 'sha256') and revoked_at is null;
  return found;
end;
$$;

create or replace function public.get_fonto_daily_login_stats(input_days integer default 7)
returns table(login_date date, login_count bigint)
language sql
security definer
set search_path = pg_catalog, public
as $$
  with dates as (
    select generate_series(
      (((now() at time zone 'Asia/Tehran')::date - (greatest(1, least(coalesce(input_days, 7), 31)) - 1))::timestamp),
      ((now() at time zone 'Asia/Tehran')::date)::timestamp,
      interval '1 day'
    )::date as day
  )
  select dates.day,
         count(e.id)::bigint
  from dates
  left join public.fonto_login_events e
    on (e.logged_in_at at time zone 'Asia/Tehran')::date = dates.day
  group by dates.day
  order by dates.day;
$$;

create or replace function public.fonto_admin_list_users()
returns table(
  id uuid, full_name text, phone text, city text, status text,
  requested_at timestamptz, password_set boolean, password_set_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if not public.is_fonto_admin() then raise exception 'دسترسی مدیر لازم است'; end if;
  return query
    select u.id, u.full_name, u.phone, u.city, u.status, u.requested_at,
           u.password_hash is not null, u.password_set_at
    from public.fonto_users u
    order by u.requested_at desc;
end;
$$;

create or replace function public.fonto_admin_set_password(input_user_id uuid, input_password text)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
begin
  if not public.is_fonto_admin() then raise exception 'دسترسی مدیر لازم است'; end if;
  if char_length(coalesce(input_password, '')) < 6 or char_length(input_password) > 64 then
    raise exception 'رمز باید بین ۶ تا ۶۴ کاراکتر باشد';
  end if;
  update public.fonto_users
  set password_hash = crypt(input_password, gen_salt('bf', 10)),
      status = 'approved', password_set_at = now(), updated_at = now()
  where id = input_user_id;
  if not found then raise exception 'درخواست پیدا نشد'; end if;
  update public.fonto_user_sessions set revoked_at = now()
  where user_id = input_user_id and revoked_at is null;
  return true;
end;
$$;

create or replace function public.fonto_admin_delete_user(input_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if not public.is_fonto_admin() then raise exception 'دسترسی مدیر لازم است'; end if;
  delete from public.fonto_users where id = input_user_id;
  return found;
end;
$$;

create or replace function public.fonto_admin_summary()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare result jsonb;
begin
  if not public.is_fonto_admin() then raise exception 'دسترسی مدیر لازم است'; end if;
  select jsonb_build_object(
    'pending_requests', count(*) filter (where status = 'pending'),
    'approved_users', count(*) filter (where status = 'approved'),
    'today_logins', (select count(*) from public.fonto_login_events where (logged_in_at at time zone 'Asia/Tehran')::date = (now() at time zone 'Asia/Tehran')::date),
    'total_logins', (select count(*) from public.fonto_login_events)
  ) into result from public.fonto_users;
  return result;
end;
$$;

-- Disable the former shared password endpoint when upgrading an existing project.
do $$
begin
  if to_regprocedure('public.verify_fonto_password(text)') is not null then
    execute 'revoke all on function public.verify_fonto_password(text) from public, anon, authenticated';
  end if;
end;
$$;

revoke all on function public.fonto_normalize_phone(text) from public, anon, authenticated;
revoke all on function public.is_fonto_admin() from public, anon;
revoke all on function public.register_fonto_user(text, text, text) from public;
revoke all on function public.verify_fonto_user(text, text) from public;
revoke all on function public.validate_fonto_session(text) from public;
revoke all on function public.revoke_fonto_session(text) from public;
revoke all on function public.get_fonto_daily_login_stats(integer) from public;
revoke all on function public.fonto_admin_list_users() from public, anon;
revoke all on function public.fonto_admin_set_password(uuid, text) from public, anon;
revoke all on function public.fonto_admin_delete_user(uuid) from public, anon;
revoke all on function public.fonto_admin_summary() from public, anon;

grant execute on function public.register_fonto_user(text, text, text) to anon, authenticated;
grant execute on function public.verify_fonto_user(text, text) to anon, authenticated;
grant execute on function public.validate_fonto_session(text) to anon, authenticated;
grant execute on function public.revoke_fonto_session(text) to anon, authenticated;
grant execute on function public.get_fonto_daily_login_stats(integer) to anon, authenticated;
grant execute on function public.is_fonto_admin() to authenticated;
grant execute on function public.fonto_admin_list_users() to authenticated;
grant execute on function public.fonto_admin_set_password(uuid, text) to authenticated;
grant execute on function public.fonto_admin_delete_user(uuid) to authenticated;
grant execute on function public.fonto_admin_summary() to authenticated;

-- Mark the existing dashboard account as the Fonto administrator.
update auth.users
set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || '{"fonto_admin": true}'::jsonb
where email = 'editors.team.ir@gmail.com';

-- Missing sales schema used by assets/js/sales-admin.js.
create table if not exists public.sale_items (
  sale_id text primary key,
  kind text not null,
  owner_name text,
  item_label text,
  thumbnail text,
  media_type text not null default 'image',
  price_toman bigint not null default 0 check (price_toman >= 0),
  active boolean not null default true,
  updated_at timestamptz not null default now()
);
create table if not exists public.sale_secrets (
  sale_id text primary key references public.sale_items(sale_id) on delete cascade,
  download_url text,
  updated_at timestamptz not null default now()
);
create table if not exists public.purchases (
  id uuid primary key default gen_random_uuid(),
  sale_id text not null references public.sale_items(sale_id),
  amount_toman bigint not null check (amount_toman >= 0),
  authority text,
  ref_id text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  paid_at timestamptz
);
create index if not exists purchases_sale_id_idx on public.purchases (sale_id);
alter table public.sale_items enable row level security;
alter table public.sale_secrets enable row level security;
alter table public.purchases enable row level security;

drop policy if exists "public read active sale items" on public.sale_items;
create policy "public read active sale items" on public.sale_items for select to anon using (active = true);
drop policy if exists "admin manage sale items" on public.sale_items;
create policy "admin manage sale items" on public.sale_items for all to authenticated
  using (public.is_fonto_admin()) with check (public.is_fonto_admin());
drop policy if exists "admin manage sale secrets" on public.sale_secrets;
create policy "admin manage sale secrets" on public.sale_secrets for all to authenticated
  using (public.is_fonto_admin()) with check (public.is_fonto_admin());
drop policy if exists "admin read purchases" on public.purchases;
create policy "admin read purchases" on public.purchases for select to authenticated
  using (public.is_fonto_admin());

revoke all on table public.sale_items from anon, authenticated;
revoke all on table public.sale_secrets from anon, authenticated;
revoke all on table public.purchases from anon, authenticated;
grant select on table public.sale_items to anon;
grant select, insert, update, delete on table public.sale_items to authenticated;
grant select, insert, update, delete on table public.sale_secrets to authenticated;
grant select on table public.purchases to authenticated;

notify pgrst, 'reload schema';
