-- EditorsTeam meeting requests
create table if not exists public.meeting_requests (
  id bigint generated by default as identity primary key,
  first_name text not null check (char_length(btrim(first_name)) between 2 and 60),
  last_name text not null check (char_length(btrim(last_name)) between 2 and 80),
  age smallint not null check (age between 10 and 100),
  phone text not null check (phone ~ '^09[0-9]{9}$'),
  created_at timestamptz not null default now()
);

alter table public.meeting_requests
  add column if not exists status text not null default 'pending',
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid='public.meeting_requests'::regclass
      and conname='meeting_requests_status_check'
  ) then
    alter table public.meeting_requests
      add constraint meeting_requests_status_check
      check (status in ('pending','contacted','completed','cancelled'));
  end if;
end $$;

create index if not exists meeting_requests_created_at_idx
  on public.meeting_requests (created_at desc);
create index if not exists meeting_requests_status_idx
  on public.meeting_requests (status, created_at desc);

alter table public.meeting_requests enable row level security;
revoke all on table public.meeting_requests from anon, authenticated;
grant usage, select on sequence public.meeting_requests_id_seq to anon, authenticated;
grant insert (first_name, last_name, age, phone) on public.meeting_requests to anon, authenticated;
grant select, update, delete on public.meeting_requests to authenticated;

-- Remove policies from the earlier prototype, if present.
drop policy if exists public_submit_meeting_request on public.meeting_requests;
drop policy if exists site_admin_read_meeting_requests on public.meeting_requests;
drop policy if exists site_admin_delete_meeting_requests on public.meeting_requests;

drop policy if exists "public can submit meeting requests" on public.meeting_requests;
create policy "public can submit meeting requests"
  on public.meeting_requests for insert to anon, authenticated
  with check (status = 'pending');

drop policy if exists "meeting admins can read" on public.meeting_requests;
create policy "meeting admins can read"
  on public.meeting_requests for select to authenticated
  using ((select public.is_fonto_admin()));

drop policy if exists "meeting admins can update" on public.meeting_requests;
create policy "meeting admins can update"
  on public.meeting_requests for update to authenticated
  using ((select public.is_fonto_admin()))
  with check ((select public.is_fonto_admin()));

drop policy if exists "meeting admins can delete" on public.meeting_requests;
create policy "meeting admins can delete"
  on public.meeting_requests for delete to authenticated
  using ((select public.is_fonto_admin()));

create or replace function public.submit_meeting_request(
  input_first_name text,
  input_last_name text,
  input_age integer,
  input_phone text
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  clean_first text := btrim(coalesce(input_first_name,''));
  clean_last text := btrim(coalesce(input_last_name,''));
  normalized_phone text := regexp_replace(
    translate(coalesce(input_phone,''),'۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩','01234567890123456789'),
    '[^0-9]','','g'
  );
begin
  if char_length(clean_first) not between 2 and 60 then raise exception 'نام معتبر نیست'; end if;
  if char_length(clean_last) not between 2 and 80 then raise exception 'نام خانوادگی معتبر نیست'; end if;
  if input_age not between 10 and 100 then raise exception 'سن معتبر نیست'; end if;
  if normalized_phone !~ '^09[0-9]{9}$' then raise exception 'شماره تلفن معتبر نیست'; end if;

  insert into public.meeting_requests(first_name,last_name,age,phone)
  values(clean_first,clean_last,input_age,normalized_phone);

  return jsonb_build_object(
    'ok',true,
    'message','درخواست شما با موفقیت ثبت شد؛ برای هماهنگی با شما تماس می‌گیریم.'
  );
end;
$$;

revoke all on function public.submit_meeting_request(text,text,integer,text) from public;
grant execute on function public.submit_meeting_request(text,text,integer,text) to anon, authenticated;
notify pgrst, 'reload schema';