-- Categorized live previews for every active Fonto font, derived from the bundled APK catalog.

begin;
set local lock_timeout = '5s';

create temporary table fonto_font_preview_seed (
  file_name text primary key,
  category text not null,
  preview_text text not null
) on commit drop;

insert into fonto_font_preview_seed (file_name, category, preview_text) values
  ('acidicTurkish.ttf', 'turkish', 'Türkçe Yazı'),
  ('Adobe arabic shin.ttf', 'arabic', 'الخط العربي'),
  ('Adobe shin stouts.ttf', 'persian', 'ایران زیبا'),
  ('afacad.ttf', 'english', 'Font Preview'),
  ('alington.otf', 'english', 'Font Preview'),
  ('AmirHafeziv2.ttf', 'persian', 'ایران زیبا'),
  ('amiri-regular.ttf', 'persian', 'ایران زیبا'),
  ('amiri-slanted.ttf', 'persian', 'ایران زیبا'),
  ('amsLekhan.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsMahaBharat.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsManoja.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsMinar.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsModi.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsPiyush.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsPremankur.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsSamanya.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsSindhu.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsSwarup.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('amsYogesh.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('ANic.ttf', 'persian', 'ایران زیبا'),
  ('ApkHu Fonts 257.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 258.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 259.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 260.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 261.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 262.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 263.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 264.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 265.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 266.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 267.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 268.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 269.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 270.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 271.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 272.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 273.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 274.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 275.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 276.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 277.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 278.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 279.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 280.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 281.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 282.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 283.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 284.TTF', 'english', 'Font Preview'),
  ('ApkHu Fonts 285.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 286.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 287.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 288.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 289.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 290.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 291.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 292.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 293.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 294.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 295.TTF', 'english', 'Font Preview'),
  ('ApkHu Fonts 296.TTF', 'english', 'Font Preview'),
  ('ApkHu Fonts 297.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 298.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 299.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 300.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 301.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 302.ttf', 'english', 'Font Preview'),
  ('ApkHu Fonts 303.ttf', 'english', 'Font Preview'),
  ('ar_arghavan.ttf', 'arabic', 'الخط العربي'),
  ('ar_arslanWessam.ttf', 'arabic', 'الخط العربي'),
  ('ar_ebhar.ttf', 'arabic', 'الخط العربي'),
  ('ar_fedra.ttf', 'arabic', 'الخط العربي'),
  ('ar_hacenCasablancaHd.ttf', 'arabic', 'الخط العربي'),
  ('ar_janna.ttf', 'arabic', 'الخط العربي'),
  ('ar_narenj.ttf', 'arabic', 'الخط العربي'),
  ('ar_rashed.ttf', 'arabic', 'الخط العربي'),
  ('ar_titrBold.ttf', 'arabic', 'الخط العربي'),
  ('ar_urw.ttf', 'arabic', 'الخط العربي'),
  ('ar_vipVatan.ttf', 'arabic', 'الخط العربي'),
  ('Aram.ttf', 'persian', 'ایران زیبا'),
  ('Aram (1).ttf', 'persian', 'ایران زیبا'),
  ('ArslanWessam.ttf', 'persian', 'ایران زیبا'),
  ('Asmae.ttf', 'persian', 'ایران زیبا'),
  ('Astrobia.otf', 'english', 'Font Preview'),
  ('Astrobia.ttf', 'english', 'Font Preview'),
  ('Aviny2.ttf', 'persian', 'ایران زیبا'),
  ('Bahman1.ttf', 'persian', 'ایران زیبا'),
  ('Bahman2.ttf', 'persian', 'ایران زیبا'),
  ('Bahman2 (1).ttf', 'persian', 'ایران زیبا'),
  ('balvardi.ttf', 'persian', 'ایران زیبا'),
  ('Bite Chocolate Personal Use.ttf', 'english', 'Font Preview'),
  ('BIZUDPGothicRegular.ttf', 'japanese', 'フォント見本'),
  ('BLACK Personal Use.ttf', 'english', 'Font Preview'),
  ('BLINDSH.ttf', 'english', 'Font Preview'),
  ('Candy Shop Black Personal Use.ttf', 'english', 'Font Preview'),
  ('Candy Shop Personal Use.ttf', 'english', 'Font Preview'),
  ('chamran.ttf', 'persian', 'ایران زیبا'),
  ('colak.ttf', 'persian', 'ایران زیبا'),
  ('copperplateclassicsanspdf.ttf', 'english', 'Font Preview'),
  ('crunch_chips.otf', 'english', 'Font Preview'),
  ('Dana-Bold.ttf', 'persian', 'ایران زیبا'),
  ('Dana-Bold (1).ttf', 'persian', 'ایران زیبا'),
  ('Death Star.otf', 'english', 'Font Preview'),
  ('DecoType Naskh Extensions.ttf', 'persian', 'ایران زیبا'),
  ('DecoType Naskh Extensions (1).ttf', 'persian', 'ایران زیبا'),
  ('DecoType Naskh Swashes.ttf', 'persian', 'ایران زیبا'),
  ('delaGothicOneRegular.ttf', 'japanese', 'フォント見本'),
  ('Deutschlander.otf', 'english', 'Font Preview'),
  ('Digi Hamishe Bold.ttf', 'persian', 'ایران زیبا'),
  ('Digi Hamishe Bold.otf', 'persian', 'ایران زیبا'),
  ('Digi Hamishe Regular.otf', 'persian', 'ایران زیبا'),
  ('Digi Hamishe Regular.ttf', 'persian', 'ایران زیبا'),
  ('Digi Hamishe Regular (1).otf', 'persian', 'ایران زیبا'),
  ('Digi Hamishe Regular (1).ttf', 'persian', 'ایران زیبا'),
  ('Digi Nozha2 Bold.ttf', 'persian', 'ایران زیبا'),
  ('Digi Nozha2 Bold.otf', 'persian', 'ایران زیبا'),
  ('Digi Nozha2 Bold (1).ttf', 'persian', 'ایران زیبا'),
  ('Digi Nozha2 Bold (1).otf', 'persian', 'ایران زیبا'),
  ('Digi Titr Circle Bold.otf', 'persian', 'ایران زیبا'),
  ('Digi Titr Circle Bold.ttf', 'persian', 'ایران زیبا'),
  ('Digi Titr Line Bold.otf', 'persian', 'ایران زیبا'),
  ('Digi Titr Line Bold.ttf', 'persian', 'ایران زیبا'),
  ('Digi Titr Plus Bold.otf', 'persian', 'ایران زیبا'),
  ('Digi Titr Plus Bold.ttf', 'persian', 'ایران زیبا'),
  ('Digi Titr Plus Bold (1).ttf', 'persian', 'ایران زیبا'),
  ('Digitalt.otf', 'english', 'Font Preview'),
  ('Digitalt.ttf', 'english', 'Font Preview'),
  ('DimaBanoo.ttf', 'persian', 'ایران زیبا'),
  ('DiodrumArabic-Bold.ttf', 'arabic', 'الخط العربي'),
  ('DiodrumArabic-Extralight.ttf', 'arabic', 'الخط العربي'),
  ('DiodrumArabic-Light.ttf', 'arabic', 'الخط العربي'),
  ('DiodrumArabic-Medium.ttf', 'arabic', 'الخط العربي'),
  ('DiodrumArabic-Regular.ttf', 'arabic', 'الخط العربي'),
  ('DiodrumArabic-Semibold.ttf', 'arabic', 'الخط العربي'),
  ('Dream Her - TTF.ttf', 'english', 'Font Preview'),
  ('Dublon-Bold(1).ttf', 'english', 'Font Preview'),
  ('Ebtekar.ttf', 'persian', 'ایران زیبا'),
  ('EMPEROR OF JAPAN-Hollow.otf', 'english', 'Font Preview'),
  ('EMPEROR OF JAPAN-Light.otf', 'english', 'Font Preview'),
  ('en_babyDoll.ttf', 'english', 'Font Preview'),
  ('en_Balinesia.otf', 'english', 'Font Preview'),
  ('en_CocogoosePro.ttf', 'english', 'Font Preview'),
  ('en_HeyComic.ttf', 'english', 'Font Preview'),
  ('en_kgReadHand.ttf', 'english', 'Font Preview'),
  ('en_LettersForLearners.ttf', 'english', 'Font Preview'),
  ('enAutography.otf', 'english', 'Font Preview'),
  ('enBebasNeueRegular.ttf', 'english', 'Font Preview'),
  ('enCheri.ttf', 'english', 'Font Preview'),
  ('enCoogoose.ttf', 'english', 'Font Preview'),
  ('encoolvetica.otf', 'english', 'Font Preview'),
  ('enDemielaFreeVersion.ttf', 'english', 'Font Preview'),
  ('enHello.ttf', 'english', 'Font Preview'),
  ('enHugMeTight.ttf', 'english', 'Font Preview'),
  ('enKidsco.otf', 'english', 'Font Preview'),
  ('enLemonMilkBold.otf', 'english', 'Font Preview'),
  ('enMorningRainbow.ttf', 'english', 'Font Preview'),
  ('enOpenSans.ttf', 'english', 'Font Preview'),
  ('enProductSans.ttf', 'english', 'Font Preview'),
  ('Estedad.ttf', 'persian', 'ایران زیبا'),
  ('exo2.ttf', 'english', 'Font Preview'),
  ('fa_a_nasr.ttf', 'persian', 'ایران زیبا'),
  ('fa_aban.ttf', 'persian', 'ایران زیبا'),
  ('fa_ain.ttf', 'persian', 'ایران زیبا'),
  ('fa_AisaBold.ttf', 'persian', 'ایران زیبا'),
  ('fa_AlmasBold.ttf', 'persian', 'ایران زیبا'),
  ('fa_amin.ttf', 'persian', 'ایران زیبا'),
  ('fa_AnBold.ttf', 'persian', 'ایران زیبا'),
  ('fa_arahel.ttf', 'persian', 'ایران زیبا'),
  ('fa_bYekan.ttf', 'persian', 'ایران زیبا'),
  ('fa_cinema.ttf', 'persian', 'ایران زیبا'),
  ('fa_darya.ttf', 'persian', 'ایران زیبا'),
  ('fa_dastnevis.ttf', 'persian', 'ایران زیبا'),
  ('fa_delbar3.ttf', 'persian', 'ایران زیبا'),
  ('fa_digi_seronaz.ttf', 'persian', 'ایران زیبا'),
  ('fa_digi_titr_bold.ttf', 'persian', 'ایران زیبا'),
  ('fa_digiMaryamRegular.ttf', 'persian', 'ایران زیبا'),
  ('fa_dima_tahriri.ttf', 'persian', 'ایران زیبا'),
  ('fa_doran.ttf', 'persian', 'ایران زیبا'),
  ('fa_dordaneh.ttf', 'persian', 'ایران زیبا'),
  ('fa_fanavari.ttf', 'persian', 'ایران زیبا'),
  ('fa_far_rozname.ttf', 'persian', 'ایران زیبا'),
  ('fa_farkhonde.ttf', 'persian', 'ایران زیبا'),
  ('fa_fedra.ttf', 'persian', 'ایران زیبا'),
  ('fa_ghaf.ttf', 'persian', 'ایران زیبا'),
  ('fa_gramoph.ttf', 'persian', 'ایران زیبا'),
  ('fa_granPaye.ttf', 'persian', 'ایران زیبا'),
  ('fa_hadye.ttf', 'persian', 'ایران زیبا'),
  ('fa_hamon.ttf', 'persian', 'ایران زیبا'),
  ('fa_heritage.ttf', 'persian', 'ایران زیبا'),
  ('fa_iranSiah.ttf', 'persian', 'ایران زیبا'),
  ('fa_jameel.ttf', 'persian', 'ایران زیبا'),
  ('fa_javan.ttf', 'persian', 'ایران زیبا'),
  ('fa_kalameh.ttf', 'persian', 'ایران زیبا'),
  ('fa_katibeh.ttf', 'persian', 'ایران زیبا'),
  ('fa_ketab3.ttf', 'persian', 'ایران زیبا'),
  ('fa_khodkar.ttf', 'persian', 'ایران زیبا'),
  ('fa_lalezar.ttf', 'persian', 'ایران زیبا'),
  ('fa_MadasiBold.ttf', 'persian', 'ایران زیبا'),
  ('fa_maha.ttf', 'persian', 'ایران زیبا'),
  ('fa_miremad.ttf', 'persian', 'ایران زیبا'),
  ('fa_mirza_bold.ttf', 'persian', 'ایران زیبا'),
  ('fa_modern.ttf', 'persian', 'ایران زیبا'),
  ('fa_molsaq.ttf', 'persian', 'ایران زیبا'),
  ('fa_moraba_bold.ttf', 'persian', 'ایران زیبا'),
  ('fa_nastaliq.ttf', 'persian', 'ایران زیبا'),
  ('fa_NegareBold.ttf', 'persian', 'ایران زیبا'),
  ('fa_NofarBold.ttf', 'persian', 'ایران زیبا'),
  ('fa_nozha.ttf', 'persian', 'ایران زیبا'),
  ('fa_Nozha2Bold.ttf', 'persian', 'ایران زیبا'),
  ('fa_paeez.ttf', 'persian', 'ایران زیبا'),
  ('fa_PaeezProfesional.ttf', 'persian', 'ایران زیبا'),
  ('fa_peyda_bold.ttf', 'persian', 'ایران زیبا'),
  ('fa_pinar_ds4_bold.ttf', 'persian', 'ایران زیبا'),
  ('fa_portada.ttf', 'persian', 'ایران زیبا'),
  ('fa_potk.ttf', 'persian', 'ایران زیبا'),
  ('fa_pouran.ttf', 'persian', 'ایران زیبا'),
  ('fa_qatar.ttf', 'persian', 'ایران زیبا'),
  ('fa_radin.ttf', 'persian', 'ایران زیبا'),
  ('fa_ray_medium.ttf', 'persian', 'ایران زیبا'),
  ('fa_san_francisco_bold.ttf', 'persian', 'ایران زیبا'),
  ('fa_sarvenaz.ttf', 'persian', 'ایران زیبا'),
  ('fa_sensSiah.ttf', 'persian', 'ایران زیبا'),
  ('fa_shakeri.ttf', 'persian', 'ایران زیبا'),
  ('fa_shams.ttf', 'persian', 'ایران زیبا'),
  ('fa_shokoh.ttf', 'persian', 'ایران زیبا'),
  ('fa_snapp.ttf', 'persian', 'ایران زیبا'),
  ('fa_sofi.ttf', 'persian', 'ایران زیبا'),
  ('fa_soroush.ttf', 'persian', 'ایران زیبا'),
  ('fa_terashin.ttf', 'persian', 'ایران زیبا'),
  ('fa_tiam.ttf', 'persian', 'ایران زیبا'),
  ('fa_titraj.ttf', 'persian', 'ایران زیبا'),
  ('fa_titrPlus.ttf', 'persian', 'ایران زیبا'),
  ('fa_yalda.ttf', 'persian', 'ایران زیبا'),
  ('fa_yekan_boom.ttf', 'persian', 'ایران زیبا'),
  ('fa_zahra.ttf', 'persian', 'ایران زیبا'),
  ('fa_zahra_rosta.ttf', 'persian', 'ایران زیبا'),
  ('Far_Naskh.ttf', 'persian', 'ایران زیبا'),
  ('farhang_sharp_bold.ttf', 'persian', 'ایران زیبا'),
  ('Feathergraphy_Clean.ttf', 'english', 'Font Preview'),
  ('Feathergraphy_Clean(1).ttf', 'english', 'Font Preview'),
  ('FontMessage.ttf', 'persian', 'ایران زیبا'),
  ('FontNegative.ttf', 'persian', 'ایران زیبا'),
  ('FontPositive.ttf', 'persian', 'ایران زیبا'),
  ('FontTitle.ttf', 'persian', 'ایران زیبا'),
  ('FontTitle (1).ttf', 'persian', 'ایران زیبا'),
  ('FTY DELIRIUM NCV.ttf', 'english', 'Font Preview'),
  ('Game Played.otf', 'english', 'Font Preview'),
  ('Game Played Outline.otf', 'english', 'Font Preview'),
  ('Gandom.ttf', 'persian', 'ایران زیبا'),
  ('Gladifilthefte.ttf', 'english', 'Font Preview'),
  ('Graphik Arabic.otf', 'arabic', 'الخط العربي'),
  ('Graphik Arabic Black.otf', 'arabic', 'الخط العربي'),
  ('Graphik Arabic Bold.otf', 'arabic', 'الخط العربي'),
  ('Graphik Arabic ExtraLight.otf', 'arabic', 'الخط العربي'),
  ('Graphik Arabic Light.otf', 'arabic', 'الخط العربي'),
  ('Graphik Arabic Medium.otf', 'arabic', 'الخط العربي'),
  ('Graphik Arabic SemiBold.otf', 'arabic', 'الخط العربي'),
  ('Graphik Arabic Super.otf', 'arabic', 'الخط العربي'),
  ('Graphik Arabic Thin.otf', 'arabic', 'الخط العربي'),
  ('Halimun.ttf', 'persian', 'ایران زیبا'),
  ('Hamideh.ttf', 'persian', 'ایران زیبا'),
  ('hanachi.ttf', 'persian', 'ایران زیبا'),
  ('HaniehOutline.ttf', 'persian', 'ایران زیبا'),
  ('Heathergreen.otf', 'english', 'Font Preview'),
  ('Hemera II DEMO.ttf', 'english', 'Font Preview'),
  ('hi_lekhan.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('hi_maha_bharat.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('hi_manoja.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('hi_minar.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('hi_modi.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('hi_piyush.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('hi_premankur.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('hi_yogesh.ttf', 'hindi', 'फ़ॉन्ट नमूना'),
  ('Hilda.ttf', 'persian', 'ایران زیبا'),
  ('I_Rounded.ttf', 'persian', 'ایران زیبا'),
  ('ID Font.TTF', 'persian', 'ایران زیبا'),
  ('IMarker.ttf', 'persian', 'ایران زیبا'),
  ('InsulaTurkish.ttf', 'turkish', 'Türkçe Yazı'),
  ('Ios 15.5 Androiland.ttf', 'persian', 'ایران زیبا'),
  ('ios_15.ttf', 'persian', 'ایران زیبا'),
  ('ios_fonto.ttf', 'persian', 'ایران زیبا'),
  ('Ios15font(@macanism_96).ttf', 'persian', 'ایران زیبا'),
  ('iranBlack.ttf', 'persian', 'ایران زیبا'),
  ('IRANMarker.ttf', 'persian', 'ایران زیبا'),
  ('IRANSansBold.ttf', 'persian', 'ایران زیبا'),
  ('IRANSansX-200.ttf', 'persian', 'ایران زیبا'),
  ('IRANSansX-500.ttf', 'persian', 'ایران زیبا'),
  ('IRANSansX-700.ttf', 'persian', 'ایران زیبا'),
  ('IRANSansX-900.ttf', 'persian', 'ایران زیبا'),
  ('IYekanBlack.ttf', 'persian', 'ایران زیبا'),
  ('JaneDoe-PersonalUse.otf', 'english', 'Font Preview'),
  ('Jellyka Delicious Cake.ttf', 'english', 'Font Preview'),
  ('joghd.ttf', 'persian', 'ایران زیبا'),
  ('JUSTICE LEAGUE.ttf', 'english', 'Font Preview'),
  ('Kalameh_Black.ttf', 'persian', 'ایران زیبا'),
  ('Kalpazan-PersonalUse.otf', 'english', 'Font Preview'),
  ('Kalpazan-PersonalUse(1).otf', 'english', 'Font Preview'),
  ('KanitLight.ttf', 'english', 'Font Preview'),
  ('khash.ttf', 'persian', 'ایران زیبا'),
  ('khaton.ttf', 'persian', 'ایران زیبا'),
  ('koloche.ttf', 'persian', 'ایران زیبا'),
  ('kosugiMaruRegular.ttf', 'japanese', 'フォント見本'),
  ('Lalezar-Regular.ttf', 'persian', 'ایران زیبا'),
  ('Library 3 am.otf', 'english', 'Font Preview'),
  ('Library 3 am soft.otf', 'english', 'Font Preview'),
  ('Madeleine.otf', 'english', 'Font Preview'),
  ('Madeleine Bold.otf', 'english', 'Font Preview'),
  ('Maneli.ttf', 'persian', 'ایران زیبا'),
  ('Mikhak-vf.ttf', 'persian', 'ایران زیبا'),
  ('Mj_Sayeh-1_0.TTF', 'persian', 'ایران زیبا'),
  ('Mj_Sayeh-2_0.TTF', 'persian', 'ایران زیبا'),
  ('MolsaqArabic-ExtraBold.ttf', 'arabic', 'الخط العربي'),
  ('monomaniacOne.ttf', 'japanese', 'フォント見本'),
  ('mRounded1c-Light.ttf', 'japanese', 'フォント見本'),
  ('namecat.ttf', 'english', 'Font Preview'),
  ('NaskhAziz.ttf', 'persian', 'ایران زیبا'),
  ('notoSans.ttf', 'japanese', 'フォント見本'),
  ('notoSerifJP.otf', 'japanese', 'フォント見本'),
  ('NOVASOLID ___.ttf', 'english', 'Font Preview'),
  ('Oliver-Regular.ttf', 'english', 'Font Preview'),
  ('openSans.ttf', 'english', 'Font Preview'),
  ('OrangeRoyaleOpen-Regular(1).ttf', 'english', 'Font Preview'),
  ('pacifico.ttf', 'english', 'Font Preview'),
  ('Pasajero.otf', 'english', 'Font Preview'),
  ('PRIMETIME-PERSONAL USE ONLY.ttf', 'english', 'Font Preview'),
  ('Red Seven.otf', 'english', 'Font Preview'),
  ('rethinkSans.ttf', 'english', 'Font Preview'),
  ('road_racer_demo.ttf', 'english', 'Font Preview'),
  ('RobotoLight.ttf', 'english', 'Font Preview'),
  ('rubikBubbles.ttf', 'english', 'Font Preview'),
  ('Shabnam-Bold.ttf', 'persian', 'ایران زیبا'),
  ('shizuruRegular.ttf', 'japanese', 'フォント見本'),
  ('shrieky.ttf', 'english', 'Font Preview'),
  ('Signatra.ttf', 'english', 'Font Preview'),
  ('Slim Play.ttf', 'english', 'Font Preview'),
  ('SNES Italic.ttf', 'english', 'Font Preview'),
  ('snowman.ttf', 'english', 'Font Preview'),
  ('sobiscuit.ttf', 'english', 'Font Preview'),
  ('Social Type Pro.otf', 'english', 'Font Preview'),
  ('Spantaran (demo).ttf', 'english', 'Font Preview'),
  ('steinemTurkish.ttf', 'turkish', 'Türkçe Yazı'),
  ('Summer-Light.otf', 'english', 'Font Preview'),
  ('Tamira-PersonalUse.otf', 'english', 'Font Preview'),
  ('Tempo.ttf', 'english', 'Font Preview'),
  ('tr_arcelik.ttf', 'turkish', 'Türkçe Yazı'),
  ('tr_balloon.ttf', 'turkish', 'Türkçe Yazı'),
  ('tr_medium.ttf', 'turkish', 'Türkçe Yazı'),
  ('tr_microgram.ttf', 'turkish', 'Türkçe Yazı'),
  ('tr_participants.ttf', 'turkish', 'Türkçe Yazı'),
  ('tr_smaching_the_quakish.ttf', 'turkish', 'Türkçe Yazı'),
  ('tr_tommaso.ttf', 'turkish', 'Türkçe Yazı'),
  ('trench100free.otf', 'english', 'Font Preview'),
  ('trench100free.ttf', 'english', 'Font Preview'),
  ('Tribalcase.otf', 'english', 'Font Preview'),
  ('turkishAnotherTypewriter.ttf', 'turkish', 'Türkçe Yazı'),
  ('turkishCourier.ttf', 'turkish', 'Türkçe Yazı'),
  ('TurkishParticipants.ttf', 'turkish', 'Türkçe Yazı'),
  ('turkishTmsRoman.ttf', 'turkish', 'Türkçe Yazı'),
  ('Vonique 92 Regular.otf', 'english', 'Font Preview'),
  ('Yahoo.ttf', 'english', 'Font Preview'),
  ('Yekan Boom.ttf', 'persian', 'ایران زیبا'),
  ('YEKAN PLUS.TTF', 'persian', 'ایران زیبا'),
  ('yekan_bakh.ttf', 'persian', 'ایران زیبا'),
  ('zenAntique.ttf', 'japanese', 'フォント見本'),
  ('Zilap Orion Personal Use.ttf', 'english', 'Font Preview'),
  ('Zilap Orion Urban Personal Use.ttf', 'english', 'Font Preview');

update public.fonto_fonts as fonts
set category = seed.category,
    preview_text = seed.preview_text
from fonto_font_preview_seed as seed
where fonts.file_name = seed.file_name;

do $$
begin
  if (select count(*) from public.fonto_fonts where is_active and file_name in (select file_name from fonto_font_preview_seed)) <> 365 then
    raise exception 'Font preview seed did not match all 365 active fonts';
  end if;
end
$$;

commit;
